#!/usr/bin/env bash

devbox_dir="${DEVBOX_ROOT}"

source "${devbox_dir}/scripts/functions.sh"

get_config_value="${devbox_dir}/scripts/get_config_value.sh"

config_path=$1
config_value=$2

status "Updating Magento config: ${config_path} = ${config_value}"
incrementNestingLevel

mysql -u"root" -p"123123q" -h"magento2-mysql" -D "$(bash ${get_config_value} "magento_database_name")" -e "INSERT INTO core_config_data
    ( scope, scope_id, path, value ) VALUES
    ( 'default', '0', '${config_path}', '${config_value}' )
     ON DUPLICATE KEY UPDATE value = '${config_value}'
;"

decrementNestingLevel
